# Generated by Django 6.0.3 on 2026-08-18 18:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('data_matricula', models.DateField(default=django.utils.timezone.localdate)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='planos.plano')),
            ],
        ),
    ]
