# Generated by Django 6.0.3 on 2026-08-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('equipamento', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
