# Generated by Django 6.1 on 2026-08-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='descricao',
        ),
    ]
