# Generated by Django 6.0.3 on 2026-08-18 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('exercicios', '0001_initial'),
        ('instrutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='alunos.aluno')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treinos', to='instrutor.instrutor')),
            ],
        ),
        migrations.CreateModel(
            name='TreinoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticoes', models.PositiveIntegerField(default=10)),
                ('carga_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('descanso_segundos', models.PositiveIntegerField(default=60)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('observacao', models.TextField(blank=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicios.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.treino')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='treino',
            name='exercicios',
            field=models.ManyToManyField(related_name='treinos', through='treinos.TreinoExercicio', to='exercicios.exercicio'),
        ),
        migrations.AddConstraint(
            model_name='treinoexercicio',
            constraint=models.UniqueConstraint(fields=('treino', 'exercicio'), name='treino_exercicio_unico'),
        ),
    ]
